### ISSUE TITLE
group by multiple columns and multiple operations on measure

### ISSUE THREAD

**Issue by manish-shukla01** [data-forge/data-forge-examples-and-tests#1]
can we get better example which shows group by more than one column and then shows average, sum of bunch of fields..like select a,b,c,sum(d), avg(3) from x group by a,b,c

**Comment by ashleydavis** [comment]
Look into the pivot function.

Examples:
https://github.com/data-forge/data-forge-ts/blob/master/src/test/dataframe.pivot-example.test.ts
https://github.com/data-forge/data-forge-ts/blob/master/src/test/dataframe.pivot-example2.test.ts
